setwd("/Users/redrock/ExData_Plotting1")
powercons <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", nrows= 2075259, stringsAsFactors=FALSE)
powercons$Date <- as.Date(powercons$Date, format = "%d/%m/%Y")
newpowerdata <- subset(powercons, subset = (Date >= "2007-02-01" & Date < "2007-02-03"))
rm(powercons)
DateTime <- paste(as.Date(newpowerdata$Date), newpowerdata$Time)
newpowerdata$DatenTime <- as.POSIXct(DateTime)
plot(newpowerdata$Global_active_power~newpowerdata$DatenTime, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.copy(png, file="plot2.png")
dev.off()