setwd("/Users/redrock/ExData_Plotting1")
powercons <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", nrows= 2075259, stringsAsFactors=FALSE)
powercons$Date <- as.Date(powercons$Date, format = "%d/%m/%Y")
newpowerdata <- subset(powercons, subset = (Date >= "2007-02-01" & Date < "2007-02-03"))
rm(powercons)
DateTime <- paste(as.Date(newpowerdata$Date), newpowerdata$Time)
newpowerdata$DatenTime <- as.POSIXct(DateTime)
with(newpowerdata, { plot(Sub_metering_1~DatenTime, type="l", ylab="Energy sub metering", xlab="")
  lines(Sub_metering_2~DatenTime, col='Red')
  lines(Sub_metering_3~DatenTime, col='Blue') })
  legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()