setwd("/Users/redrock/ExData_Plotting1")
powercons <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", nrows= 2075259, stringsAsFactors=FALSE)
powercons$Date <- as.Date(powercons$Date, format = "%d/%m/%Y")
newpowerdata <- subset(powercons, subset = (Date >= "2007-02-01" & Date < "2007-02-03"))
rm(powercons)
DateTime <- paste(as.Date(newpowerdata$Date), newpowerdata$Time)
newpowerdata$DatenTime <- as.POSIXct(DateTime)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(newpowerdata, { plot(Global_active_power~DatenTime, type = "l", ylab = "Global Active Power", xlab = "")
                     plot(Voltage~DatenTime, type="l", ylab="Voltage", xlab="datetime")
                     plot(Sub_metering_1~DatenTime, type="l", ylab="Energy sub metering", xlab="")
                     lines(Sub_metering_2~DatenTime, col='Red')
                     lines(Sub_metering_3~DatenTime, col='Blue')
                     legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
                     plot(Global_reactive_power~DatenTime, type="l", ylab="Global_rective_power", xlab="datetime")
})
dev.copy(png, file="plot4.png")
dev.off()